### ISSUE TITLE
Subjects & projects: unique names

### ISSUE THREAD

**Issue by pcklink** [VisionandCognition/OpenAccessStorage#2]
Primates are pretty much always involved in multiple projects, if not in parallel, then for sure over time. This could also be the case for other species.

I understand that in the database there is no unique linking, but getdbfields.m does give this impression, which could be confusing. 

Alternatively, a very clear manual that explains things like this would also solve this.

**Comment by chrisvdt** [comment]
Subjects are associated with projects. Subjects are all unique, but can be associated with different projects. If you would like to use a subject from another project you should click the new button. But now instead of generating a new subject you can select a known subject from the list underneath to associate it with your project.
